package pack;

import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fairuz Zamrody (19051397056)
 */
public class tubesPbo extends javax.swing.JFrame {

    /**
     * Creates new form tubesPbo
     */
    Bioskop b = new Bioskop("Bioskop A", "Jl. Apa aja no.5");
    int noStudio;
    ArrayList<JamTayang> jt;
    Kursi[][] k;
    int statusPesan, index; 
    public tubesPbo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bPesanTiket = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();
        bAdminLogin = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        panelPesanStudio = new javax.swing.JPanel();
        textBResStudio1 = new javax.swing.JTextField();
        textBResStudio3 = new javax.swing.JTextField();
        textBResStudio2 = new javax.swing.JTextField();
        textBResStudio4 = new javax.swing.JTextField();
        textBResStudio5 = new javax.swing.JTextField();
        bResStudio1 = new javax.swing.JButton();
        bResStudio2 = new javax.swing.JButton();
        bResStudio3 = new javax.swing.JButton();
        bResStudio4 = new javax.swing.JButton();
        bResStudio5 = new javax.swing.JButton();
        bCancelPesanStudio = new javax.swing.JButton();
        panelDetailStudio = new javax.swing.JPanel();
        labelNamaStudio = new javax.swing.JLabel();
        texFieldNamaFilm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        texFieldSinopsis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboJamTayang = new javax.swing.JComboBox();
        bNextToPickKursi = new javax.swing.JButton();
        bCancelDetail = new javax.swing.JButton();
        panelKursi = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        comboKursi = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        bSelectKursi = new javax.swing.JButton();
        bCancelKursi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        texAreaKursi = new javax.swing.JTextArea();
        panelLogin = new javax.swing.JPanel();
        bLogin = new javax.swing.JButton();
        passFieldAdmin = new javax.swing.JPasswordField();
        panelEditStudio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bEditStudio2 = new javax.swing.JButton();
        bEditStudio1 = new javax.swing.JButton();
        bEditStudio3 = new javax.swing.JButton();
        bEditStudio4 = new javax.swing.JButton();
        bEditStudio5 = new javax.swing.JButton();
        bCancelAdminStudio = new javax.swing.JButton();
        panelEditDetailStudio = new javax.swing.JPanel();
        labelStudioEdit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        texFieldEditNamaFilm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        texAreaEditSinopsis = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        spinJam = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        spinMenit = new javax.swing.JSpinner();
        editAddJamTayang = new javax.swing.JButton();
        bFinish = new javax.swing.JButton();
        editCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texAreaJamTayang = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.CardLayout());

        panelMenu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("APLIKASI TIKET BIOSKOP");

        bPesanTiket.setText("PEMESANAN TIKET");
        bPesanTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesanTiketActionPerformed(evt);
            }
        });

        bBatal.setText("PEMBATALAN");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        bAdminLogin.setText("ADMIN");
        bAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdminLoginActionPerformed(evt);
            }
        });

        bExit.setText("KELUAR");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPesanTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(bPesanTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel2.add(panelMenu, "card2");

        textBResStudio1.setEditable(false);
        textBResStudio1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBResStudio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBResStudio1ActionPerformed(evt);
            }
        });

        textBResStudio3.setEditable(false);
        textBResStudio3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBResStudio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBResStudio3ActionPerformed(evt);
            }
        });

        textBResStudio2.setEditable(false);
        textBResStudio2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBResStudio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBResStudio2ActionPerformed(evt);
            }
        });

        textBResStudio4.setEditable(false);
        textBResStudio4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textBResStudio5.setEditable(false);
        textBResStudio5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bResStudio1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bResStudio1.setText("STUDIO 1");
        bResStudio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResStudio1ActionPerformed(evt);
            }
        });

        bResStudio2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bResStudio2.setText("STUDIO 2");
        bResStudio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResStudio2ActionPerformed(evt);
            }
        });

        bResStudio3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bResStudio3.setText("STUDIO 3");
        bResStudio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResStudio3ActionPerformed(evt);
            }
        });

        bResStudio4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bResStudio4.setText("STUDIO 4");
        bResStudio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResStudio4ActionPerformed(evt);
            }
        });

        bResStudio5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bResStudio5.setText("STUDIO 5");
        bResStudio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResStudio5ActionPerformed(evt);
            }
        });

        bCancelPesanStudio.setText("CANCEL");
        bCancelPesanStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelPesanStudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPesanStudioLayout = new javax.swing.GroupLayout(panelPesanStudio);
        panelPesanStudio.setLayout(panelPesanStudioLayout);
        panelPesanStudioLayout.setHorizontalGroup(
            panelPesanStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPesanStudioLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(panelPesanStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPesanStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPesanStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textBResStudio3)
                            .addComponent(textBResStudio1)
                            .addComponent(textBResStudio4)
                            .addComponent(textBResStudio2)
                            .addComponent(textBResStudio5)
                            .addGroup(panelPesanStudioLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(bResStudio5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bCancelPesanStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPesanStudioLayout.createSequentialGroup()
                            .addComponent(bResStudio4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(88, 88, 88))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPesanStudioLayout.createSequentialGroup()
                            .addComponent(bResStudio3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91)))
                    .addGroup(panelPesanStudioLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(panelPesanStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bResStudio2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bResStudio1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)))
                .addGap(64, 64, 64))
        );
        panelPesanStudioLayout.setVerticalGroup(
            panelPesanStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesanStudioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bResStudio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBResStudio1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bResStudio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBResStudio2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bResStudio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBResStudio3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bResStudio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBResStudio4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bResStudio5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBResStudio5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCancelPesanStudio, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(panelPesanStudio, "card3");

        labelNamaStudio.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        labelNamaStudio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNamaStudio.setText("STUDIO 1");

        texFieldNamaFilm.setEditable(false);

        jLabel3.setText("Nama Film");

        jLabel5.setText("Sinopsis");

        texFieldSinopsis.setEditable(false);

        jLabel6.setText("Jam Tayang");

        bNextToPickKursi.setText("NEXT");
        bNextToPickKursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNextToPickKursiActionPerformed(evt);
            }
        });

        bCancelDetail.setText("CANCEL");
        bCancelDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetailStudioLayout = new javax.swing.GroupLayout(panelDetailStudio);
        panelDetailStudio.setLayout(panelDetailStudioLayout);
        panelDetailStudioLayout.setHorizontalGroup(
            panelDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailStudioLayout.createSequentialGroup()
                .addGroup(panelDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailStudioLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(labelNamaStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetailStudioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDetailStudioLayout.createSequentialGroup()
                                .addComponent(bCancelDetail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bNextToPickKursi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDetailStudioLayout.createSequentialGroup()
                                .addGroup(panelDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetailStudioLayout.createSequentialGroup()
                                        .addGroup(panelDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetailStudioLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)))
                                .addGroup(panelDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboJamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texFieldSinopsis, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                    .addComponent(texFieldNamaFilm))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelDetailStudioLayout.setVerticalGroup(
            panelDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailStudioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNamaStudio)
                .addGap(32, 32, 32)
                .addGroup(panelDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texFieldNamaFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panelDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(texFieldSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboJamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(panelDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelDetail)
                    .addComponent(bNextToPickKursi))
                .addGap(41, 41, 41))
        );

        jPanel2.add(panelDetailStudio, "card4");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("KURSI");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("No kursi ");

        bSelectKursi.setText("PESAN");
        bSelectKursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelectKursiActionPerformed(evt);
            }
        });

        bCancelKursi.setText("CANCEL");
        bCancelKursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelKursiActionPerformed(evt);
            }
        });

        jButton1.setText("FINISH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        texAreaKursi.setColumns(20);
        texAreaKursi.setRows(5);
        jScrollPane2.setViewportView(texAreaKursi);

        javax.swing.GroupLayout panelKursiLayout = new javax.swing.GroupLayout(panelKursi);
        panelKursi.setLayout(panelKursiLayout);
        panelKursiLayout.setHorizontalGroup(
            panelKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKursiLayout.createSequentialGroup()
                .addGroup(panelKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKursiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addGroup(panelKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCancelKursi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelKursiLayout.createSequentialGroup()
                        .addGroup(panelKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelKursiLayout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel16))
                            .addGroup(panelKursiLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboKursi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bSelectKursi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelKursiLayout.setVerticalGroup(
            panelKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKursiLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addGap(39, 39, 39)
                .addGroup(panelKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(panelKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboKursi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bSelectKursi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(panelKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelKursiLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelKursi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(panelKursi, "card5");

        bLogin.setText("LOGIN");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passFieldAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(passFieldAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jPanel2.add(panelLogin, "card6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("EDIT STUDIO");

        bEditStudio2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bEditStudio2.setText("STUDIO 2");
        bEditStudio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditStudio2ActionPerformed(evt);
            }
        });

        bEditStudio1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bEditStudio1.setText("STUDIO 1");
        bEditStudio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditStudio1ActionPerformed(evt);
            }
        });

        bEditStudio3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bEditStudio3.setText("STUDIO 3");
        bEditStudio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditStudio3ActionPerformed(evt);
            }
        });

        bEditStudio4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bEditStudio4.setText("STUDIO 4");
        bEditStudio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditStudio4ActionPerformed(evt);
            }
        });

        bEditStudio5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bEditStudio5.setText("STUDIO 5");
        bEditStudio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditStudio5ActionPerformed(evt);
            }
        });

        bCancelAdminStudio.setText("CANCEL");
        bCancelAdminStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelAdminStudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditStudioLayout = new javax.swing.GroupLayout(panelEditStudio);
        panelEditStudio.setLayout(panelEditStudioLayout);
        panelEditStudioLayout.setHorizontalGroup(
            panelEditStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditStudioLayout.createSequentialGroup()
                .addGroup(panelEditStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditStudioLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(panelEditStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCancelAdminStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEditStudioLayout.createSequentialGroup()
                                .addComponent(bEditStudio1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bEditStudio2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bEditStudio3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEditStudioLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(bEditStudio4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bEditStudio5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelEditStudioLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel7)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelEditStudioLayout.setVerticalGroup(
            panelEditStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditStudioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEditStudio1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEditStudio2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEditStudio3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEditStudio5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEditStudio4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bCancelAdminStudio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelEditStudio, "card7");

        labelStudioEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelStudioEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStudioEdit.setText("STUDIO 1");

        jLabel10.setText("Nama Film");

        texFieldEditNamaFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldEditNamaFilmActionPerformed(evt);
            }
        });

        jLabel11.setText("Sinopsis");

        jLabel12.setText("Jam Tayang");

        spinJam.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"}));

        jLabel13.setText("Jam");

        jLabel14.setText("Menit");

        spinMenit.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"}));

        editAddJamTayang.setText("ADD");
        editAddJamTayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAddJamTayangActionPerformed(evt);
            }
        });

        bFinish.setText("FINISH");
        bFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinishActionPerformed(evt);
            }
        });

        editCancel.setText("CANCEL");
        editCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCancelActionPerformed(evt);
            }
        });

        texAreaJamTayang.setEditable(false);
        texAreaJamTayang.setColumns(20);
        texAreaJamTayang.setRows(5);
        jScrollPane1.setViewportView(texAreaJamTayang);

        javax.swing.GroupLayout panelEditDetailStudioLayout = new javax.swing.GroupLayout(panelEditDetailStudio);
        panelEditDetailStudio.setLayout(panelEditDetailStudioLayout);
        panelEditDetailStudioLayout.setHorizontalGroup(
            panelEditDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditDetailStudioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditDetailStudioLayout.createSequentialGroup()
                        .addGroup(panelEditDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelEditDetailStudioLayout.createSequentialGroup()
                                .addGroup(panelEditDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEditDetailStudioLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(panelEditDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texFieldEditNamaFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texAreaEditSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEditDetailStudioLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinJam, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinMenit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editAddJamTayang)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditDetailStudioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(panelEditDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bFinish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditDetailStudioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelStudioEdit)
                .addGap(163, 163, 163))
        );
        panelEditDetailStudioLayout.setVerticalGroup(
            panelEditDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditDetailStudioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelStudioEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(texFieldEditNamaFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelEditDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditDetailStudioLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel11)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditDetailStudioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(texAreaEditSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelEditDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinMenit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAddJamTayang)
                    .addComponent(spinJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panelEditDetailStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEditDetailStudioLayout.createSequentialGroup()
                        .addComponent(bFinish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editCancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        jPanel2.add(panelEditDetailStudio, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textBResStudio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBResStudio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBResStudio3ActionPerformed

    private void texFieldEditNamaFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldEditNamaFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldEditNamaFilmActionPerformed

    private void bPesanTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesanTiketActionPerformed
        panelMenu.setVisible(false);
        comboJamTayang.removeAllItems();
        statusPesan = 1;
        if (b.getStudio(1).getFilm() == null) {
            textBResStudio1.setText("Tidak ada film");
        } else {
            textBResStudio1.setText(b.getStudio(1).getFilm().getNamaFilm());
        }
        if (b.getStudio(2).getFilm() == null) {
            textBResStudio2.setText("Tidak ada film");
        } else {
            textBResStudio2.setText(b.getStudio(2).getFilm().getNamaFilm());
        }
        if (b.getStudio(3).getFilm() == null) {
            textBResStudio3.setText("Tidak ada film");
        } else {
            textBResStudio3.setText(b.getStudio(3).getFilm().getNamaFilm());
        }
        if (b.getStudio(4).getFilm() == null) {
            textBResStudio4.setText("Tidak ada film");
        } else {
            textBResStudio4.setText(b.getStudio(4).getFilm().getNamaFilm());
        }
        if (b.getStudio(5).getFilm() == null) {
            textBResStudio5.setText("Tidak ada film");
        } else {
            textBResStudio5.setText(b.getStudio(5).getFilm().getNamaFilm());
        }
        panelPesanStudio.setVisible(true);
    }//GEN-LAST:event_bPesanTiketActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        statusPesan = 2;
        comboJamTayang.removeAllItems();
        if (b.getStudio(1).getFilm() == null) {
            textBResStudio1.setText("Tidak ada film");
        } else {
            textBResStudio1.setText(b.getStudio(1).getFilm().getNamaFilm());
        }
        if (b.getStudio(2).getFilm() == null) {
            textBResStudio2.setText("Tidak ada film");
        } else {
            textBResStudio2.setText(b.getStudio(2).getFilm().getNamaFilm());
        }
        if (b.getStudio(3).getFilm() == null) {
            textBResStudio3.setText("Tidak ada film");
        } else {
            textBResStudio3.setText(b.getStudio(3).getFilm().getNamaFilm());
        }
        if (b.getStudio(4).getFilm() == null) {
            textBResStudio4.setText("Tidak ada film");
        } else {
            textBResStudio4.setText(b.getStudio(4).getFilm().getNamaFilm());
        }
        if (b.getStudio(5).getFilm() == null) {
            textBResStudio5.setText("Tidak ada film");
        } else {
            textBResStudio5.setText(b.getStudio(5).getFilm().getNamaFilm());
        }
        panelPesanStudio.setVisible(true);
        panelMenu.setVisible(false);
        panelPesanStudio.setVisible(true);
    }//GEN-LAST:event_bBatalActionPerformed

    private void bAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdminLoginActionPerformed
        panelMenu.setVisible(false);
        passFieldAdmin.setText(null);
        panelLogin.setVisible(true);
    }//GEN-LAST:event_bAdminLoginActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_bExitActionPerformed

    private void bResStudio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResStudio1ActionPerformed
        if (b.getStudio(1).getFilm() != null) {
            labelNamaStudio.setText("Studio 1");
            texFieldNamaFilm.setText(b.getStudio(1).getFilm().getNamaFilm());
            texFieldSinopsis.setText(b.getStudio(1).getFilm().getSinopsis());
            noStudio = 1;
            for (JamTayang j : b.getStudio(1).getList()) {
                comboJamTayang.addItem(j.getJam());
            }
            jt = b.getStudio(1).getList();
            panelPesanStudio.setVisible(false);
            panelDetailStudio.setVisible(true);
        }
    }//GEN-LAST:event_bResStudio1ActionPerformed

    private void textBResStudio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBResStudio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBResStudio2ActionPerformed

    private void bResStudio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResStudio2ActionPerformed
        if (b.getStudio(2).getFilm() != null) {
            labelNamaStudio.setText("Studio 2");
            texFieldNamaFilm.setText(b.getStudio(2).getFilm().getNamaFilm());
            texFieldSinopsis.setText(b.getStudio(2).getFilm().getSinopsis());
            noStudio = 2;
            for (JamTayang j : b.getStudio(2).getList()) {
                comboJamTayang.addItem(j.getJam());
            }
            jt = b.getStudio(2).getList();
            panelPesanStudio.setVisible(false);
            panelDetailStudio.setVisible(true);
        }
    }//GEN-LAST:event_bResStudio2ActionPerformed

    private void bResStudio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResStudio3ActionPerformed
        if (b.getStudio(3).getFilm() != null) {
            labelNamaStudio.setText("Studio 3");
            texFieldNamaFilm.setText(b.getStudio(3).getFilm().getNamaFilm());
            texFieldSinopsis.setText(b.getStudio(3).getFilm().getSinopsis());
            noStudio = 3;
            for (JamTayang j : b.getStudio(3).getList()) {
                comboJamTayang.addItem(j.getJam());
            }
            jt = b.getStudio(3).getList();
            panelPesanStudio.setVisible(false);
            panelDetailStudio.setVisible(true);
        }
    }//GEN-LAST:event_bResStudio3ActionPerformed

    private void bResStudio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResStudio4ActionPerformed
        if (b.getStudio(4).getFilm() != null) {
            labelNamaStudio.setText("Studio 4");
            texFieldNamaFilm.setText(b.getStudio(4).getFilm().getNamaFilm());
            texFieldSinopsis.setText(b.getStudio(4).getFilm().getSinopsis());
            noStudio = 4;
            for (JamTayang j : b.getStudio(4).getList()) {
                comboJamTayang.addItem(j.getJam());
            }
            jt = b.getStudio(4).getList();
            panelPesanStudio.setVisible(false);
            panelDetailStudio.setVisible(true);
        }
    }//GEN-LAST:event_bResStudio4ActionPerformed

    private void bResStudio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResStudio5ActionPerformed
        if (b.getStudio(5).getFilm() != null) {
            labelNamaStudio.setText("Studio 5");
            texFieldNamaFilm.setText(b.getStudio(5).getFilm().getNamaFilm());
            texFieldSinopsis.setText(b.getStudio(5).getFilm().getSinopsis());
            noStudio = 5;
            for (JamTayang j : b.getStudio(5).getList()) {
                comboJamTayang.addItem(j.getJam());
            }
            jt = b.getStudio(5).getList();
            panelPesanStudio.setVisible(false);
            panelDetailStudio.setVisible(true);
        }
    }//GEN-LAST:event_bResStudio5ActionPerformed

    private void bCancelPesanStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelPesanStudioActionPerformed
        panelPesanStudio.setVisible(false);
        panelMenu.setVisible(true);
    }//GEN-LAST:event_bCancelPesanStudioActionPerformed

    private void bCancelDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelDetailActionPerformed
        panelDetailStudio.setVisible(false);
        panelMenu.setVisible(true);
    }//GEN-LAST:event_bCancelDetailActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        panelLogin.setVisible(false);
        String pass = new String(passFieldAdmin.getPassword());
        if (pass.equals("Admin")) {
            panelEditStudio.setVisible(true);
        } else {
            panelMenu.setVisible(true);
        }
    }//GEN-LAST:event_bLoginActionPerformed

    private void bCancelAdminStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelAdminStudioActionPerformed
        panelEditStudio.setVisible(false);
        panelMenu.setVisible(true);
    }//GEN-LAST:event_bCancelAdminStudioActionPerformed

    private void textBResStudio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBResStudio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBResStudio1ActionPerformed

    private void bEditStudio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditStudio1ActionPerformed
        labelStudioEdit.setText("Studio 1");
        noStudio = 1;
        jt = new ArrayList<>();
        texAreaJamTayang.setText("Jam tayang film baru :\n");
        panelEditStudio.setVisible(false);
        texFieldEditNamaFilm.setText(null);
        texAreaEditSinopsis.setText(null);
        panelEditDetailStudio.setVisible(true);
    }//GEN-LAST:event_bEditStudio1ActionPerformed

    private void bEditStudio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditStudio2ActionPerformed
        labelStudioEdit.setText("Studio 2");
        jt = new ArrayList<>();
        texAreaJamTayang.setText("Jam tayang film baru :\n");
        noStudio = 2;
        panelEditStudio.setVisible(false);
        texFieldEditNamaFilm.setText(null);
        texAreaEditSinopsis.setText(null);
        panelEditDetailStudio.setVisible(true);
    }//GEN-LAST:event_bEditStudio2ActionPerformed

    private void bEditStudio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditStudio3ActionPerformed
        labelStudioEdit.setText("Studio 3");
        jt = new ArrayList<>();
        texAreaJamTayang.setText("Jam tayang film baru :\n");
        noStudio = 3;
        panelEditStudio.setVisible(false);
        texFieldEditNamaFilm.setText(null);
        texAreaEditSinopsis.setText(null);
        panelEditDetailStudio.setVisible(true);
    }//GEN-LAST:event_bEditStudio3ActionPerformed

    private void bEditStudio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditStudio4ActionPerformed
        labelStudioEdit.setText("Studio 4");
        jt = new ArrayList<>();
        texAreaJamTayang.setText("Jam tayang film baru :\n");
        noStudio = 4;
        panelEditStudio.setVisible(false);
        texFieldEditNamaFilm.setText(null);
        texAreaEditSinopsis.setText(null);
        panelEditDetailStudio.setVisible(true);
    }//GEN-LAST:event_bEditStudio4ActionPerformed

    private void bEditStudio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditStudio5ActionPerformed
        labelStudioEdit.setText("Studio 5");
        jt = new ArrayList<>();
        texAreaJamTayang.setText("Jam tayang film baru :\n");
        noStudio = 5;
        panelEditStudio.setVisible(false);
        texFieldEditNamaFilm.setText(null);
        texAreaEditSinopsis.setText(null);
        panelEditDetailStudio.setVisible(true);
    }//GEN-LAST:event_bEditStudio5ActionPerformed

    private void bFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinishActionPerformed
        b.setFilmToStudio(noStudio, texFieldEditNamaFilm.getText(), texAreaEditSinopsis.getText(), jt);
        panelEditDetailStudio.setVisible(false);
        panelMenu.setVisible(true);
    }//GEN-LAST:event_bFinishActionPerformed

    private void editAddJamTayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAddJamTayangActionPerformed
        String jam = (String) spinJam.getValue() + ":" + (String) spinMenit.getValue();
        jt.add(new JamTayang(jam));
        texAreaJamTayang.setText(texAreaJamTayang.getText() + "-" + jam + "\n");
    }//GEN-LAST:event_editAddJamTayangActionPerformed

    private void bNextToPickKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNextToPickKursiActionPerformed
        index = comboJamTayang.getSelectedIndex();
        k = jt.get(comboJamTayang.getSelectedIndex()).getKursi();
        String s = "";
        for (int x = 0; x < 6; x++) {
            for (int y = 0; y < 5; y++) {
                if (statusPesan == 1) {
                    if (!k[x][y].isReserved()) {
                        comboKursi.addItem(k[x][y].getNoKursi());
                    }         
                } else if (statusPesan == 2) {
                    if (k[x][y].isReserved()) {
                        comboKursi.addItem(k[x][y].getNoKursi());
                    }
                }
            }  
        }
        if (statusPesan == 1) {
            bSelectKursi.setText("Pesan");
            texAreaKursi.setText("Kursi yang dipesan :\n");
        } else {
            bSelectKursi.setText("Batal");
            texAreaKursi.setText("");
        }
        panelDetailStudio.setVisible(false);
        panelKursi.setVisible(true);
    }//GEN-LAST:event_bNextToPickKursiActionPerformed

    private void bSelectKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelectKursiActionPerformed
        String s = "";
        int m = -1;
        int n = 0;
        boolean found = false;
        while (!found) {
            while (!found && m < 4) {
                m++;
		if (k[n][m].getNoKursi().equals(((String)comboKursi.getSelectedItem()))) {
                    if (statusPesan == 1) {
                        k[n][m].setReserved(true);
                        texAreaKursi.setText(texAreaKursi.getText() + k[n][m].getNoKursi() + "; ");
                    } else {
                        texAreaKursi.setText("Pemesanan kursi nomor " + k[n][m].getNoKursi() + " dibatalkan");
                        k[n][m].setReserved(false);
                    }
                    s = k[n][m].getNoKursi();
                    found = true;
		}
            }
            m = -1;
            n++;
        }
        comboKursi.removeItem(s);
    }//GEN-LAST:event_bSelectKursiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jt.get(comboJamTayang.getSelectedIndex()).setKursi(k);
        b.studio[noStudio].updateJamTayang(jt);
        comboKursi.removeAllItems();
        panelKursi.setVisible(false);
        panelMenu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCancelActionPerformed
        panelEditDetailStudio.setVisible(false);
        panelMenu.setVisible(true);
    }//GEN-LAST:event_editCancelActionPerformed

    private void bCancelKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelKursiActionPerformed
        panelKursi.setVisible(false);
        panelMenu.setVisible(true);
    }//GEN-LAST:event_bCancelKursiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tubesPbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tubesPbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tubesPbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tubesPbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tubesPbo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdminLogin;
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bCancelAdminStudio;
    private javax.swing.JButton bCancelDetail;
    private javax.swing.JButton bCancelKursi;
    private javax.swing.JButton bCancelPesanStudio;
    private javax.swing.JButton bEditStudio1;
    private javax.swing.JButton bEditStudio2;
    private javax.swing.JButton bEditStudio3;
    private javax.swing.JButton bEditStudio4;
    private javax.swing.JButton bEditStudio5;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bFinish;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bNextToPickKursi;
    private javax.swing.JButton bPesanTiket;
    private javax.swing.JButton bResStudio1;
    private javax.swing.JButton bResStudio2;
    private javax.swing.JButton bResStudio3;
    private javax.swing.JButton bResStudio4;
    private javax.swing.JButton bResStudio5;
    private javax.swing.JButton bSelectKursi;
    private javax.swing.JComboBox comboJamTayang;
    private javax.swing.JComboBox comboKursi;
    private javax.swing.JButton editAddJamTayang;
    private javax.swing.JButton editCancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNamaStudio;
    private javax.swing.JLabel labelStudioEdit;
    private javax.swing.JPanel panelDetailStudio;
    private javax.swing.JPanel panelEditDetailStudio;
    private javax.swing.JPanel panelEditStudio;
    private javax.swing.JPanel panelKursi;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPesanStudio;
    private javax.swing.JPasswordField passFieldAdmin;
    private javax.swing.JSpinner spinJam;
    private javax.swing.JSpinner spinMenit;
    private javax.swing.JTextField texAreaEditSinopsis;
    private javax.swing.JTextArea texAreaJamTayang;
    private javax.swing.JTextArea texAreaKursi;
    private javax.swing.JTextField texFieldEditNamaFilm;
    private javax.swing.JTextField texFieldNamaFilm;
    private javax.swing.JTextField texFieldSinopsis;
    private javax.swing.JTextField textBResStudio1;
    private javax.swing.JTextField textBResStudio2;
    private javax.swing.JTextField textBResStudio3;
    private javax.swing.JTextField textBResStudio4;
    private javax.swing.JTextField textBResStudio5;
    // End of variables declaration//GEN-END:variables
}